.gitignore, README.md, pom.xml, src/main/java/com/vaadin/ui/radiobutton/GeneratedVaadinRadioButton.java, src/main/java/com/vaadin/ui/radiobutton/GeneratedVaadinRadioGroup.java, src/main/java/com/vaadin/ui/radiobutton/RadioButton.java, src/main/java/com/vaadin/ui/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/ui/radiobutton/RadioButtonGroupIT.java, src/test/java/com/vaadin/ui/radiobutton/RadioButtonGroupView.java
Fix for #7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/13)
=> Radio button group initial implementation

src/main/java/com/vaadin/ui/radiobutton/RadioButton.java, src/main/java/com/vaadin/ui/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/ui/radiobutton/RadioButtonGroupIT.java, src/test/java/com/vaadin/ui/radiobutton/RadioButtonGroupView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/15)
=> Add item enabled provider for radio button group

.gitignore, pom.xml, src/main/java/com/vaadin/ui/radiobutton/RadioButton.java, src/main/java/com/vaadin/ui/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/ui/radiobutton/RadioButtonGroupIT.java, src/test/java/com/vaadin/ui/radiobutton/RadioButtonGroupView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/16)
=> Use ComponentRenderer for RadioButtonGroup

src/main/java/com/vaadin/ui/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/ui/radiobutton/RadioButtonGroupIT.java, src/test/java/com/vaadin/ui/radiobutton/RadioButtonGroupView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/14)
=> Use ItemLabelGenerator for radio button group.

src/test/java/com/vaadin/ui/radiobutton/RadioButtonGroupIT.java, src/test/java/com/vaadin/ui/radiobutton/RadioButtonGroupView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/18)
=> Demo for icon generator with RadioButtonGroup

src/test/java/com/vaadin/ui/radiobutton/demo/RadioButtonGroupView.java, src/test/java/com/vaadin/ui/radiobutton/tests/RadioButtonGroupIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/21)
=> refactor the component repo structure

src/test/java/com/vaadin/ui/radiobutton/demo/RadioButtonGroupView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/22)
=> Remove redundant generics type

src/main/java/com/vaadin/ui/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/ui/radiobutton/demo/RadioButtonGroupView.java, src/test/java/com/vaadin/ui/radiobutton/tests/RadioButtonGroupIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/23)
=> Add components between radio buttons

src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java, src/main/java/com/vaadin/flow/component/radiobutton/RadioButton.java, src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java, src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java
Part of the fix for the #3032
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/24)
=> Rename package com.vaadin.ui to com.vaadin.flow.component

src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java, src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java
The part of the package rename #3032
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/25)
=> Update imports due package rename in the server module

src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/26)
=> Correct import in IT tests

src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java, src/test/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/28)
=> Update generated component and add lumo style to demos

src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java, src/main/java/com/vaadin/flow/component/radiobutton/RadioButton.java, src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java, src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java
Fix for #2329
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/29)
=> Update generated components and reverse accessors for "disabled"

pom.xml, src/test/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java
renaming repository ids;
remove HtmlImport from component demo;
enable logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/31)
=> Using new webjars

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/32)
=> Fix artifact deployment.

pom.xml, src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/33)
=> Update classes to use the new ComponentRenderers

src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java, src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
fix after vaadin/flow#3678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/37)
=> Update generated code

pom.xml, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/38)
=> Update webcomponent to 1.0.0-beta2

src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
Fixes #35
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/41)
=> Override the on enabled state change for radioButtonGroup.

src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
The isEnabled method should be used form
HasEnabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/42)
=> Remove overridden isEnabled method.

src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/43)
=> Method name updated from Change to Changed

pom.xml, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/44)
=> Update vaadin-radio-button to 1.0.0

src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java, src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java
If the user removes the disabled attribute from the
radiobutton the server should not accept the new value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/48)
=> Wrong selection of a disabled item should revert.

src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java, src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/49)
=> Adapt main components to new hasValue API

src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/51)
=> Update items when toggling readonly status

pom.xml, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/54)
=> Update vaadin-radio-button to 1.0.1

pom.xml, src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonSerializableTest.java
Related to vaadin/platform#173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/55)
=> Add serialization test

src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java, src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java
Extends the IT test to check the client side value along with the server
side value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/57)
=> Add logic which reset the value back for disabled button back

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/62)
=> Update README about branching scheme

pom.xml, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java, src/main/java/com/vaadin/flow/component/radiobutton/RadioGroupVariant.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/64)
=> Update to webjars with Material theme

src/test/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java, src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/68)
=> Add theme variant demo and tests

src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java, src/test/java/com/vaadin/flow/component/radiobutton/tests/Entity.java, src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java, src/test/java/com/vaadin/flow/component/radiobutton/tests/RequiredValidationIT.java, src/test/java/com/vaadin/flow/component/radiobutton/tests/RequiredValidationPage.java
Related to #12 #58;
Demo the usage of label and error message;
Tests on added APIs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/69)
=> Add APIs for setting label, error message and required

src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/flow/component/radiobutton/tests/RefreshDataProviderPage.java, src/test/java/com/vaadin/flow/component/radiobutton/tests/RefreshDataProviderPageIT.java
Fixes #75
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/76)
=> Reset the component on data provider refresh

src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java, src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java, src/main/java/com/vaadin/flow/component/radiobutton/RadioGroupVariant.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/74)
=> Update java wrapper to stable version

src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, src/test/java/com/vaadin/flow/component/radiobutton/tests/RefreshDataProviderPage.java, src/test/java/com/vaadin/flow/component/radiobutton/tests/RefreshDataProviderPageIT.java
Fixes #75
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/77)
=> Reset the component on data provider refresh 

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/88)
=> Update flow version to 1.5

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/89)
=> Update flow version to 1.4

vaadin-radio-button-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/87)
=> Update web jar version to 1.1.5

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/90)
=> Update flow-component-base version

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/92)
=> Update base version to 1.3-SNAPSHOT

pom.xml, vaadin-radio-button-flow-demo/pom.xml, vaadin-radio-button-flow-integration-tests/pom.xml, vaadin-radio-button-flow-testbench/pom.xml, vaadin-radio-button-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/93)
=> Update to next minor

vaadin-radio-button-flow-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/95)
=> Make TB artifactId consistent with other components

pom.xml, vaadin-radio-button-flow-integration-tests/pom-bower-mode.xml, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioButton.java, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/96)
=> Add bower mode tests.

vaadin-radio-button-flow-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/97)
=> Use flow-maven-plugin in integration test

vaadin-radio-button-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/98)
=> Update webjar versions

pom.xml, vaadin-radio-button-flow-testbench/pom.xml, vaadin-radio-button-flow-testbench/src/main/java/com/vaadin/flow/component/radiobutton/testbench/RadioButtonGroupElement.java, vaadin-radio-button-flow/pom.xml
Use common interfaces from testbench-core
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/99)
=> Remove vaadin-components-testbench

vaadin-radio-button-flow/pom.xml, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButton.java, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/101)
=> Update WC version

pom.xml, vaadin-radio-button-flow-integration-tests/pom-bower-mode.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/103)
=> Fix integration test build

vaadin-radio-button-flow/pom.xml, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButton.java, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/104)
=> Bump vaadin-radio-button wc dependency to 1.2.2

vaadin-radio-button-flow/pom.xml, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButton.java, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/105)
=> Bump vaadin-radio-button wc dependency to 1.2.3

vaadin-radio-button-flow-demo/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/109)
=> Only use flow-maven-plugin when packaging is war

vaadin-radio-button-flow-demo/pom.xml, vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java, vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/data/DepartmentData.java, vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/entity/Department.java, vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDemoPage.java, vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java, vaadin-radio-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupViewDemoPage.java
Fix #110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/114)
=> Fix radio button group demos

vaadin-radio-button-flow/pom.xml, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButton.java, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
This is a PR for `2.0` branch. It contains demo changes and a web component fix.
=> Update web component to 1.2.4

vaadin-radio-button-flow/pom.xml, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButton.java, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
This is a PR for 2.0 branch (V14)
=> Update web component version to 1.2.5

vaadin-radio-button-flow-demo/src/main/java/com/vaadin/flow/component/radiobutton/demo/RadioButtonGroupView.java
This issue is for users to be able to use code correctly by copy-pasting
Depends on https://github.com/vaadin/flow/pull/8199/files
=> Adding missing method to Vaadin Radio Group demos

pom.xml, vaadin-radio-button-flow-demo/pom.xml, vaadin-radio-button-flow-integration-tests/pom-bower-mode.xml, vaadin-radio-button-flow-integration-tests/pom.xml, vaadin-radio-button-flow-testbench/pom.xml, vaadin-radio-button-flow/pom.xml, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButton.java, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
* Bump snapshot version
* Bump flow-component-base (2.3-SNAPSHOT)
* Bump WC dependency
* Bump webjar dependencies
Part of vaadin/components-team-tasks#534
=> Bump versions for V14.3

vaadin-radio-button-flow/pom.xml, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java, vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java
=> Add and use explicit CTOR to avoid overwriting Element property value

vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
=> fix: prevent possible memory leak (#153)
